# 命名空间
server:
  servlet:
    context-path: /console
# spring配置
spring:
  profiles:
    active: dev
  application:
    name: Ray Console
  servlet:
    multipart:
      # 请求数据大小
      max-request-size: 100MB
      # 上传文件大小
      max-file-size: 100MB
  # 时间正反序列化格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: RAY-TOKEN
  # token有效期，单位s 默认1天, -1代表永不过期
  timeout: 604800
  # 是否允许同一账号并发登录(为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时(为true共用一个token, 为false每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 开启日志
  is-log: true
  # 是否写入到Header中
  is-write-header: true
# 系统配置
ray:
  framework:
    core:
      redis:
        # 关闭redis事务功能
        transaction: false
      auth:
        # 全部的API都需要登录认证，除了在exclude-paths中的API
        include-path: /**
        # 以下API无需登录认证
        exclude-paths:
          - /v1/auth/v1/login-vc
          - /v1/auth/v1/login
      mybatis:
        tenant:
          # 开启租户插件
          enable: true
          # 租户字段名称
          columnName: tenant_code
          # 忽略租户隔离的表名
          ignoresTables:
            - sys_dict
            - sys_dict_item
            - sys_func
            - sys_role
            - sys_role_func_relation
            - sys_role_user_relation
    sdk:
      verify-code:
        # 验证码缓存过期时间
        expiration: 2m
        # 图片宽度
        captchaImgWidth: 127
        # 图片高度
        captchaImgHeight: 40
        # 验证码答案长度
        captchaLength: 2
